name: Test Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release/*  
      - feature/*
      - bugfix/*
  pull_request:
    branches:
      - main    

jobs:
  build:
   runs-on: windows-2025
   steps:
    - name: Test
      run: |
       echo "Test"
       echo "ORGVAR1: ${{vars.ORGVAR1}}"
       echo "ORGVAR2: ${{vars.ORGVAR2}}"
       
       echo "REPOVAR1: ${{vars.REPOVAR1}}"
       echo "REPOVAR2: ${{vars.REPOVAR2}}"

    # path to the action file
    - name: Test2
      uses: sancr7org/MyServiceOrg/.github/actions/test@main

    # okay to run like this for once QD
    - name: Test3
      uses: sancr7org/MyServiceOrg/.github/workflows/test_dispatch@main
