name: Calling Reusable Workflow

#on:
#  workflow_dispatch:
#  push:
#    branches:  [main]
#  pull_request:
#    branches:  [main]
    
on:
  workflow_dispatch:
    inputs:
      param1:
        description: 'test1'
        required: true
        default: 'param1'
      param2:
        description: 'Version to run'
        required: true
        default: 'param2'

jobs:
  caller_job:
    uses: sancr7org/MyServiceOrg/.github/workflows/test_workflow_call.yml@main
    with:
      param1: ${{inputs.param1}}
      param2: ${{inputs.param2}}
