name: Calling Reusable Workflow

#on:
#  workflow_dispatch:
#  push:
#    branches:  [main]
#  pull_request:
#    branches:  [main]
    
on:
  workflow_dispatch:
    inputs:
      param1:
        description: 'test1'
        required: true
        default: 'param1'
      param2:
        description: 'Version to run'
        required: true
        default: 'param2'
  push:
     branches: [main, feature/*, bug/*]
  pull_request:
     branches: [main, feature/*, bug/*]

# run-name: ${{ github.event_name == 'workflow_dispatch' && format('CI/CD-{0}-branch-{1}', tojson(inputs), github.ref_name) || '' }}
#run-name: Deploy to ${{ inputs.param1 }} by @${{ github.actor }}
# Dynamically set the run name to include the type of branch (feature or bugfix), branch name, and the user
run-name: "${{ contains(github.head_ref, 'feature/') && 'Feature' || contains(github.head_ref, 'bugf/') && 'Bug' || 'Update' }}: ${{ github.head_ref }} by @${{ github.actor }}"

jobs:
  caller_job:
    uses: sancr7org/MyServiceOrg/.github/workflows/test_workflow_call.yml@main
    with:
      param1: ${{inputs.param1}}
      param2: ${{inputs.param2}}
