name: Calling Reusable Workflow

#on:
#  workflow_dispatch:
#  push:
#    branches:  [main]
#  pull_request:
#    branches:  [main]
    
on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Name of the service'
        required: true
        default: 'rabbitmq'
      version:
        description: 'Version to run'
        required: false
        default: 'v1.0'

jobs:
  caller_job:
    uses: sancr7org/MyServiceOrg/.github/workflows/test_workflow_call.yml@main
    with:
      param1: "test1"
      param2: "test2"
