name: Calling Reusable Workflow

on:
  workflow_dispatch:
  push:
    branches:  [main]
  pull_request:
    branches:  [main]

jobs:
  caller_job:
    uses: sancr7org/MyServiceOrg/.github/workflows/test_workflow_call.yml@main
    with:
      param1: "test1"
      param2: "test2"
