name: Dispatch on Workflow Call

# this workflow can take inputs and run the jobs
# this is a resuable workflow
# to run this from UI, this has to be triggered atleast once? or required=true ?
on:
  workflow_call:
    inputs:
      param1:
        description: 'test1'
        required: true
        type: string
      param2:
        description: 'test2'
        required: true
        type: string
    secrets:
       secret1:
         required: false


jobs:
  build:
   runs-on: windows-2025
   steps:
    - name: Test
      run: |
       echo "Test"
       echo "ORGVAR1: ${{vars.ORGVAR1}}"
       echo "ORGVAR2: ${{vars.ORGVAR2}}"
       
       echo "REPOVAR1: ${{vars.REPOVAR1}}"
       echo "REPOVAR2: ${{vars.REPOVAR2}}"
    
    #- name: Test2
    #  uses: ./github/actions/test@main 
